apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment-tcp
  labels:
    app: iperf-server-tcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iperf-server-tcp
  template:
    metadata:
      labels:
        app: iperf-server-tcp
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - master
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf-server-tcp
        image: lroktu/iperf 
        args: ['-s', '-p', '5201']
        command: [iperf]
        ports:
        - containerPort: 5201
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Service
metadata:
  name: iperf-server-tcp
spec:
  selector:
    app: iperf-server-tcp
  ports:
  - protocol: TCP
    port: 5201
    targetPort: server
    
---
    
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-client
  labels:
    app: iperf-client
spec:
  selector:
    matchLabels:
      app: iperf-client
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf-client
        image: lroktu/iperf
        command: ['/bin/sh', '-c', 'sleep infinity']
      terminationGracePeriodSeconds: 0
