// Copyright 2020-present Open Networking Foundation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.8.0
// source: bf.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This message describes the public Barefoot specific definition of a single P4
// program. It is passed to Stratum as the p4 device config of the P4Runtime
// ForwardingPipelineConfig message.
type BfPipelineConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P4Name        string                      `protobuf:"bytes,1,opt,name=p4_name,json=p4Name,proto3" json:"p4_name,omitempty"`                      // name for this P4 program
	BfruntimeInfo []byte                      `protobuf:"bytes,2,opt,name=bfruntime_info,json=bfruntimeInfo,proto3" json:"bfruntime_info,omitempty"` // bfrt.json file
	Profiles      []*BfPipelineConfig_Profile `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`                                // list of profiles for this program
}

func (x *BfPipelineConfig) Reset() {
	*x = BfPipelineConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfPipelineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfPipelineConfig) ProtoMessage() {}

func (x *BfPipelineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_bf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfPipelineConfig.ProtoReflect.Descriptor instead.
func (*BfPipelineConfig) Descriptor() ([]byte, []int) {
	return file_bf_proto_rawDescGZIP(), []int{0}
}

func (x *BfPipelineConfig) GetP4Name() string {
	if x != nil {
		return x.P4Name
	}
	return ""
}

func (x *BfPipelineConfig) GetBfruntimeInfo() []byte {
	if x != nil {
		return x.BfruntimeInfo
	}
	return nil
}

func (x *BfPipelineConfig) GetProfiles() []*BfPipelineConfig_Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// Internal storage format that contains all the information of a P4 program
// that can be loaded into the SDE.
type BfrtDeviceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Programs []*BfrtDeviceConfig_P4Program `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
}

func (x *BfrtDeviceConfig) Reset() {
	*x = BfrtDeviceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfrtDeviceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfrtDeviceConfig) ProtoMessage() {}

func (x *BfrtDeviceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_bf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfrtDeviceConfig.ProtoReflect.Descriptor instead.
func (*BfrtDeviceConfig) Descriptor() ([]byte, []int) {
	return file_bf_proto_rawDescGZIP(), []int{1}
}

func (x *BfrtDeviceConfig) GetPrograms() []*BfrtDeviceConfig_P4Program {
	if x != nil {
		return x.Programs
	}
	return nil
}

type BfPipelineConfig_Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileName string   `protobuf:"bytes,1,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`   // name for this profile
	Context     []byte   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`                              // context.json file
	Binary      []byte   `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`                                // tofino.bin file
	PipeScope   []uint32 `protobuf:"varint,4,rep,packed,name=pipe_scope,json=pipeScope,proto3" json:"pipe_scope,omitempty"` // list of hardware pipes for this profile
}

func (x *BfPipelineConfig_Profile) Reset() {
	*x = BfPipelineConfig_Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfPipelineConfig_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfPipelineConfig_Profile) ProtoMessage() {}

func (x *BfPipelineConfig_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_bf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfPipelineConfig_Profile.ProtoReflect.Descriptor instead.
func (*BfPipelineConfig_Profile) Descriptor() ([]byte, []int) {
	return file_bf_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BfPipelineConfig_Profile) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *BfPipelineConfig_Profile) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *BfPipelineConfig_Profile) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *BfPipelineConfig_Profile) GetPipeScope() []uint32 {
	if x != nil {
		return x.PipeScope
	}
	return nil
}

type BfrtDeviceConfig_P4Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // For display purposes only.
	Bfrt      []byte                                   `protobuf:"bytes,2,opt,name=bfrt,proto3" json:"bfrt,omitempty"` // JSON
	P4Info    *P4Info                                  `protobuf:"bytes,3,opt,name=p4info,proto3" json:"p4info,omitempty"`
	Pipelines []*BfrtDeviceConfig_P4Program_P4Pipeline `protobuf:"bytes,4,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
}

func (x *BfrtDeviceConfig_P4Program) Reset() {
	*x = BfrtDeviceConfig_P4Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfrtDeviceConfig_P4Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfrtDeviceConfig_P4Program) ProtoMessage() {}

func (x *BfrtDeviceConfig_P4Program) ProtoReflect() protoreflect.Message {
	mi := &file_bf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfrtDeviceConfig_P4Program.ProtoReflect.Descriptor instead.
func (*BfrtDeviceConfig_P4Program) Descriptor() ([]byte, []int) {
	return file_bf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BfrtDeviceConfig_P4Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BfrtDeviceConfig_P4Program) GetBfrt() []byte {
	if x != nil {
		return x.Bfrt
	}
	return nil
}

func (x *BfrtDeviceConfig_P4Program) GetP4Info() *P4Info {
	if x != nil {
		return x.P4Info
	}
	return nil
}

func (x *BfrtDeviceConfig_P4Program) GetPipelines() []*BfrtDeviceConfig_P4Program_P4Pipeline {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type BfrtDeviceConfig_P4Program_P4Pipeline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`           // For display purposes only.
	Scope   []uint32 `protobuf:"varint,2,rep,packed,name=scope,proto3" json:"scope,omitempty"` // List of pipes this profile is applied to.
	Context []byte   `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`     // JSON
	Config  []byte   `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`       // tofino.bin
}

func (x *BfrtDeviceConfig_P4Program_P4Pipeline) Reset() {
	*x = BfrtDeviceConfig_P4Program_P4Pipeline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BfrtDeviceConfig_P4Program_P4Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfrtDeviceConfig_P4Program_P4Pipeline) ProtoMessage() {}

func (x *BfrtDeviceConfig_P4Program_P4Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_bf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfrtDeviceConfig_P4Program_P4Pipeline.ProtoReflect.Descriptor instead.
func (*BfrtDeviceConfig_P4Program_P4Pipeline) Descriptor() ([]byte, []int) {
	return file_bf_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *BfrtDeviceConfig_P4Program_P4Pipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BfrtDeviceConfig_P4Program_P4Pipeline) GetScope() []uint32 {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *BfrtDeviceConfig_P4Program_P4Pipeline) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *BfrtDeviceConfig_P4Program_P4Pipeline) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_bf_proto protoreflect.FileDescriptor

var file_bf_proto_rawDesc = []byte{
	0x0a, 0x08, 0x62, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c,
	0x70, 0x34, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x02, 0x0a,
	0x10, 0x42, 0x66, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x34, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x34, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x66,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0d, 0x62, 0x66, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x66, 0x50, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x7d, 0x0a, 0x07, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x69, 0x70, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x09, 0x70, 0x69, 0x70, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x22, 0xdb, 0x02, 0x0a, 0x10, 0x42,
	0x66, 0x72, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x3a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x66, 0x72, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x34, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x8a, 0x02, 0x0a, 0x09,
	0x50, 0x34, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x66, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x66, 0x72,
	0x74, 0x12, 0x22, 0x0a, 0x06, 0x70, 0x34, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x34, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70,
	0x34, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x47, 0x0a, 0x09, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x66,
	0x72, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50,
	0x34, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x50, 0x34, 0x50, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x09, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x1a, 0x68,
	0x0a, 0x0a, 0x50, 0x34, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bf_proto_rawDescOnce sync.Once
	file_bf_proto_rawDescData = file_bf_proto_rawDesc
)

func file_bf_proto_rawDescGZIP() []byte {
	file_bf_proto_rawDescOnce.Do(func() {
		file_bf_proto_rawDescData = protoimpl.X.CompressGZIP(file_bf_proto_rawDescData)
	})
	return file_bf_proto_rawDescData
}

var file_bf_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bf_proto_goTypes = []interface{}{
	(*BfPipelineConfig)(nil),                      // 0: pb.BfPipelineConfig
	(*BfrtDeviceConfig)(nil),                      // 1: pb.BfrtDeviceConfig
	(*BfPipelineConfig_Profile)(nil),              // 2: pb.BfPipelineConfig.Profile
	(*BfrtDeviceConfig_P4Program)(nil),            // 3: pb.BfrtDeviceConfig.P4Program
	(*BfrtDeviceConfig_P4Program_P4Pipeline)(nil), // 4: pb.BfrtDeviceConfig.P4Program.P4Pipeline
	(*P4Info)(nil),                                // 5: pb.P4Info
}
var file_bf_proto_depIdxs = []int32{
	2, // 0: pb.BfPipelineConfig.profiles:type_name -> pb.BfPipelineConfig.Profile
	3, // 1: pb.BfrtDeviceConfig.programs:type_name -> pb.BfrtDeviceConfig.P4Program
	5, // 2: pb.BfrtDeviceConfig.P4Program.p4info:type_name -> pb.P4Info
	4, // 3: pb.BfrtDeviceConfig.P4Program.pipelines:type_name -> pb.BfrtDeviceConfig.P4Program.P4Pipeline
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bf_proto_init() }
func file_bf_proto_init() {
	if File_bf_proto != nil {
		return
	}
	file_p4info_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfPipelineConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfrtDeviceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfPipelineConfig_Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfrtDeviceConfig_P4Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BfrtDeviceConfig_P4Program_P4Pipeline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bf_proto_goTypes,
		DependencyIndexes: file_bf_proto_depIdxs,
		MessageInfos:      file_bf_proto_msgTypes,
	}.Build()
	File_bf_proto = out.File
	file_bf_proto_rawDesc = nil
	file_bf_proto_goTypes = nil
	file_bf_proto_depIdxs = nil
}
